In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

In [3]:
hello=tf.constant('Hello, Tensorflou!')

In [4]:
print(hello)

tf.Tensor(b'Hello, Tensorflou!', shape=(), dtype=string)


In [5]:
const_a=tf.constant(5)
const_b=tf.constant(9)
total = const_a + const_b
print(total)

tf.Tensor(14, shape=(), dtype=int32)


In [6]:
node1=tf.constant(5,dtype=tf.int32)
node2=tf.constant(6,dtype=tf.int32)
node3=tf.add(node1,node2)
print(node3)

tf.Tensor(11, shape=(), dtype=int32)


In [7]:
node4=tf.subtract(node1,node2)
print(node4)

tf.Tensor(-1, shape=(), dtype=int32)


In [8]:
div=tf.math.truediv(node1,node2)
print(div)

tf.Tensor(0.8333333333333334, shape=(), dtype=float64)


In [9]:
rand_a=tf.random.normal([3,1],2.0)
rand_b=tf.random.uniform([3,2],1.0,4.0)

In [10]:
print(rand_a)

tf.Tensor(
[[2.773815  ]
 [2.0934386 ]
 [0.89128757]], shape=(3, 1), dtype=float32)


In [11]:
print(rand_b)

tf.Tensor(
[[2.397732  2.695125 ]
 [1.1544377 3.112995 ]
 [3.8669567 1.018583 ]], shape=(3, 2), dtype=float32)


In [ ]:
multi=tf.math.multiply(rand_a,rand_b)

In [13]:
print(multi)

tf.Tensor(
[[6.650865   7.475778  ]
 [2.4167445  6.516864  ]
 [3.4465704  0.90785044]], shape=(3, 2), dtype=float32)
