In [1]:
import tensorflow as tf

In [2]:
changeable=tf.Variable([5,3])
unchangeable=tf.constant([3,5])
changeable, unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 3])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5])>)

In [3]:
changeable[0]=1

TypeError: 'ResourceVariable' object does not support item assignment

In [4]:
changeable[0].assign(1)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3])>

In [24]:
# 3 matrizes, de 3 linhas e 6 colunas
tensor=tf.ones([3,3,6])
print(tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(3, 3, 6), dtype=float32)


In [13]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to one (1).



In [19]:
# os primeiros dois elementos de cada dimensão
tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [36]:
print(tensor.dtype)#data type
print(tensor.ndim)#número de dimensões
print(tensor.shape[-1])#número de elementos do última eixo
print(tf.size(tensor))#total de elementos do tensor

<dtype: 'float32'>
3
6
tf.Tensor(54, shape=(), dtype=int32)


In [38]:
tensor2=tf.constant([[10, 7],[3, 4]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [44]:
tensor2[-1,-1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>